FROM alpine:3.11

RUN apk update

RUN apk add mysql mysql-client openrc

RUN openrc
RUN touch /run/openrc/softlevel
RUN /etc/init.d/mariadb setup


COPY ./src/start.sh /
COPY ./src/my_db.sql /
COPY ./src/mariadb-server.cnf /etc/my.cnf.d/

RUN chmod +x start.sh

EXPOSE 3306

CMD ["sh", "start.sh"]