FROM alpine:3.11

RUN apk update

RUN apk add mysql mysql-client openrc

RUN openrc
RUN touch /run/openrc/softlevel
RUN /etc/init.d/mariadb setup

RUN apk add telegraf --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/
COPY ./src/telegraf.conf /etc

COPY ./src/start.sh /
COPY ./src/liveness.sh /
COPY ./src/my_db.sql /
COPY ./src/mariadb-server.cnf /etc/my.cnf.d/

RUN chmod 777 start.sh

EXPOSE 3306

CMD ["sh", "start.sh"]