FROM alpine:3.11

RUN apk update
RUN apk add nginx openrc vim openssl
RUN mkdir -p /run/nginx
RUN openssl req -x509 -nodes -days 365 -subj "/C=CA/ST=QC/O=Company, Inc./CN=mydomain.com" -addext "subjectAltName=DNS:mydomain.com" -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt;

RUN rc-status
RUN touch /run/openrc/softlevel

COPY ./src/default.conf /etc/nginx/conf.d/
COPY ./src/index.html /var/www/localhost/htdocs
COPY ./src/start.sh /

RUN chmod +x start.sh

EXPOSE 80 443

CMD ["sh", "start.sh"]