#Deployment : tool to manage how pods gonna workd (replica , ports ...)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
#spec field specifies exactly what I want k8s to build  
spec:
  #selector > I want from dplymnt to search for all pods with the label app : nginx
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        imagePullPolicy: Never
        #assign/create  ports
        ports:
        - containerPort: 80
        - containerPort: 443
        # livenessProbe:
        #   exec:
        #     command:
        #     - bash
        #     - /health.sh
        #   initialDelaySeconds: 35
        #   periodSeconds: 5
---
  #service : instead of contacting each pod with its own ip address we use service to communicate with a single ip address
  #by using metallb
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
    #access ports  , the port of service entry point , which in my case gonna ge the same as the pods by default ,
    #because I don't assign the ports in targetPort
  ports:
      #name is optional , but if you have more than port then you must name each one
    - name: http
      protocol: TCP
      #service port
      port: 80
    - name: https
      protocol: TCP
      port: 443