FROM alpine:3.11

RUN apk update
RUN apk add nginx openrc vim php7 php7-fpm php7-opcache php7-gd php7-mysqli php7-zlib php7-curl php7-xml php7-json php7-iconv php7-session php-mbstring


COPY ./src/phpmyadmin/ /var/www/phpmyadmin

COPY ./src/default.conf /etc/nginx/conf.d

COPY ./src/start.sh  /

RUN rc-status
RUN touch /run/openrc/softlevel

EXPOSE 5000

CMD ["sh", "start.sh"]