FROM alpine:3.11

RUN apk apdate
RUN apk add openrc php7 php7-fpm php7-mysqli

RUN mkdir -p /run/nginx

COPY ./src/default.conf /etc/nginx/conf.d/
COPY ./src/wordpress /var/www/localhost/htdocs/

EXPOSE 5050