apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - image: wordpress
          name: wordpress
          imagePullPolicy: Never
          ports:
          - containerPort: 5050
          livenessProbe:
            exec:
              command:
                - sh
                - liveness.sh
            initialDelaySeconds: 35
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  #unique
  name: wordpress
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
    - port: 5050
      name: http
      protocol: TCP