FROM alpine:3.11

RUN apk update
RUN apk upgrade
RUN apk add openrc openssl vsftpd libc6-compat

RUN mkdir -p /etc/ssl/private
RUN mkdir -p /etc/ssl/certs

RUN adduser -D admin -G root && echo "admin:admin" | chpasswd
RUN chown -R admin:root /etc/vsftpd
RUN yes "" | openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/vsftpd.key -out /etc/ssl/certs/vsftpd.crt
COPY ./src/vsftpd.conf /etc/vsftpd/vsftpd.conf

RUN apk add telegraf --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/
COPY ./src/telegraf.conf /etc

COPY ./src/start.sh /
COPY ./src/liveness.sh /

RUN chmod 777 /start.sh

EXPOSE 20 21 30000 30001

CMD ["sh", "start.sh"]